//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplier
    {
        public string SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPassword { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string WebAddress { get; set; }
        public string OrdersEmail { get; set; }
        public string vdn { get; set; }
        public string EmailCCInfo { get; set; }
        public string AllowAnonymous { get; set; }
        public string BuyerRegistration { get; set; }
        public string BuyerRegistrationEmail { get; set; }
        public string BCCSuperAdmin { get; set; }
        public string @decimal { get; set; }
        public string UPSTools { get; set; }
        public string AdminLocale { get; set; }
        public Nullable<int> TimeOffSet { get; set; }
        public string Workflow { get; set; }
        public string Invoicing { get; set; }
        public string QtyPricingTable { get; set; }
        public string DraftCart { get; set; }
        public string Notes { get; set; }
        public string Attributes { get; set; }
        public string InventoryUpload { get; set; }
        public string MarketingLists { get; set; }
        public string CustomPages { get; set; }
        public string ApplicationType { get; set; }
        public Nullable<bool> IsNotifyOrderError { get; set; }
    }
}
